CREATE TABLE [prodcopystg].[Emma__Emma_Group__c]
(
[Id] [nvarchar] (18) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[IsDeleted] [bit] NULL,
[Name] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[CreatedDate] [datetime] NULL,
[CreatedById] [nvarchar] (18) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[LastModifiedDate] [datetime] NULL,
[LastModifiedById] [nvarchar] (18) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[SystemModstamp] [datetime] NULL,
[LastViewedDate] [datetime] NULL,
[LastReferencedDate] [datetime] NULL,
[OwnerId] [nvarchar] (18) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[LastActivityDate] [date] NULL,
[emma__Auto_Refresh_Group_Members__c] [bit] NULL,
[emma__Batch_Error_Message__c] [nvarchar] (1000) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[emma__Batch_Status__c] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[emma__Emma_Group_ID__c] [nvarchar] (80) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[emma__Last_Synced_Date__c] [datetime] NULL,
[emma__Members_in_Emma__c] [float] NULL,
[emma__Report_Field_Name__c] [nvarchar] (1000) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[emma__Report_Folder_Name__c] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[emma__Report_ID__c] [nvarchar] (18) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[emma__Report_Link__c] [nvarchar] (1300) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[emma__Report_Run_Date__c] [datetime] NULL,
[emma__Sync_Message__c] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[emma__Sync_Status__c] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[emma__Total_Members__c] [float] NULL,
[emma__Imported_Members__c] [float] NULL,
[emma__Num_of_Contacts__c] [float] NULL,
[emma__Num_of_Leads__c] [float] NULL,
[emma__Num_of_Non_Contact_Lead_Members__c] [float] NULL,
[emma__Number_of_Pending_Memberships__c] [float] NULL,
[emma__Total_Unique_Members__c] [float] NULL,
[copyloaddate] [datetime] NULL CONSTRAINT [DF__Emma__Emm__copyl__07C12930] DEFAULT (getdate())
)
GO
