CREATE TABLE [prodcopystg].[Emma__Emma_Email__c]
(
[Id] [nvarchar] (18) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[IsDeleted] [bit] NULL,
[Name] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[CreatedDate] [datetime] NULL,
[CreatedById] [nvarchar] (18) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[LastModifiedDate] [datetime] NULL,
[LastModifiedById] [nvarchar] (18) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[SystemModstamp] [datetime] NULL,
[LastViewedDate] [datetime] NULL,
[LastReferencedDate] [datetime] NULL,
[emma__Date_Opened__c] [datetime] NULL,
[LastActivityDate] [date] NULL,
[emma__Emma_Mailing__c] [nvarchar] (18) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[emma__Contact__c] [nvarchar] (18) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[emma__Exclude_from_Rollup__c] [bit] NULL,
[emma__Lead__c] [nvarchar] (18) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[emma__Mailing_ID__c] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[emma__Member_Name__c] [nvarchar] (1300) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[emma__Member_Type__c] [nvarchar] (1300) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[emma__Message_ID__c] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[emma__Num_of_Clicks__c] [float] NULL,
[emma__Num_of_Facebook_ClicksFx__c] [float] NULL,
[emma__Num_of_Facebook_Clicks__c] [float] NULL,
[emma__Num_of_Facebook_SharesFx__c] [float] NULL,
[emma__Num_of_Facebook_Shares__c] [float] NULL,
[emma__Num_of_ForwardsFx__c] [float] NULL,
[emma__Num_of_Forwards__c] [float] NULL,
[emma__Num_of_LinkedIn_ClicksFx__c] [float] NULL,
[emma__Num_of_LinkedIn_Clicks__c] [float] NULL,
[emma__Num_of_LinkedIn_SharesFx__c] [float] NULL,
[emma__Num_of_LinkedIn_Shares__c] [float] NULL,
[emma__Num_of_OpensFx__c] [float] NULL,
[emma__Num_of_Opens__c] [float] NULL,
[emma__Num_of_SharesFx__c] [float] NULL,
[emma__Num_of_Shares__c] [float] NULL,
[emma__Num_of_Twitter_ClicksFx__c] [float] NULL,
[emma__Num_of_Twitter_Clicks__c] [float] NULL,
[emma__Num_of_Twitter_SharesFx__c] [float] NULL,
[emma__Num_of_Twitter_Shares__c] [float] NULL,
[emma__Number_Of_ClicksFx__c] [float] NULL,
[emma__Opened__c] [nvarchar] (1300) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[emma__Use_PreCalc_Summary__c] [bit] NULL,
[emma__View_In_Emma__c] [nvarchar] (1300) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[emma__Summary_Num_of_Clicks__c] [float] NULL,
[emma__Summary_Num_of_Facebook_Clicks__c] [float] NULL,
[emma__Summary_Num_of_Facebook_Shares__c] [float] NULL,
[emma__Summary_Num_of_Forwards__c] [float] NULL,
[emma__Summary_Num_of_LinkedIn_Clicks__c] [float] NULL,
[emma__Summary_Num_of_LinkedIn_Shares__c] [float] NULL,
[emma__Summary_Num_of_Opens__c] [float] NULL,
[emma__Summary_Num_of_Shares__c] [float] NULL,
[emma__Summary_Num_of_Twitter_Clicks__c] [float] NULL,
[emma__Summary_Num_of_Twitter_Shares__c] [float] NULL,
[copyloaddate] [datetime] NULL CONSTRAINT [DF__Emma__Emm__copyl__114A936A] DEFAULT (getdate())
)
WITH
(
DATA_COMPRESSION = PAGE
)
GO
CREATE CLUSTERED INDEX [CIX_Emma__Emma_Email__c_Id] ON [prodcopystg].[Emma__Emma_Email__c] ([Id]) WITH (DATA_COMPRESSION = PAGE)
GO
