CREATE TABLE [prodcopystg].[Transaction__c]
(
[Id] [nvarchar] (18) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[IsDeleted] [bit] NULL,
[Name] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[CreatedDate] [datetime] NULL,
[CreatedById] [nvarchar] (18) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[LastModifiedDate] [datetime] NULL,
[LastModifiedById] [nvarchar] (18) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[SystemModstamp] [datetime] NULL,
[SSB_CRMSYSTEM_CONTACT_ID__c] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[QtySeat__c] [float] NULL,
[AccountID__c] [nvarchar] (18) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[TicketingAccountID__c] [float] NULL,
[IsComp__c] [bit] NULL,
[EventDate__c] [date] NULL,
[FactTicketSalesID__c] [float] NULL,
[Item__c] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[ItemName__c] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[OrderDate__c] [date] NULL,
[OrderLine__c] [float] NULL,
[OrderNumber__c] [float] NULL,
[OwedAmount__c] [float] NULL,
[PaidAmount__c] [float] NULL,
[PriceCode__c] [nvarchar] (6) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[PromoCode__c] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[RowName__c] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[SalesRep__c] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[SeasonName__c] [nvarchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Seat__c] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[SeatPrice__c] [float] NULL,
[SectionName__c] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Team__c] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Total__c] [float] NULL,
[copyloaddate] [datetime] NULL CONSTRAINT [DF__Transacti__copyl__3B40CD36] DEFAULT (getdate()),
[ContactID__c] [nvarchar] (18) COLLATE SQL_Latin1_General_CP1_CI_AS NULL
)
GO
ALTER TABLE [prodcopystg].[Transaction__c] ADD CONSTRAINT [pk_id_stgtransaction] PRIMARY KEY CLUSTERED  ([Id])
GO
