CREATE TABLE [prodcopy].[hed_Address__c]
(
[Id] [nvarchar] (18) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[IsDeleted] [bit] NULL,
[Name] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[OwnerId] [nvarchar] (18) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[CreatedDate] [datetime] NULL,
[CreatedById] [nvarchar] (18) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[LastModifiedDate] [datetime] NULL,
[LastModifiedById] [nvarchar] (18) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[SystemModstamp] [datetime] NULL,
[LastViewedDate] [datetime] NULL,
[LastReferencedDate] [datetime] NULL,
[hed__Address_Type__c] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[hed__Default_Address__c] [bit] NULL,
[hed__Formula_MailingAddress__c] [nvarchar] (1300) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[hed__Formula_MailingStreetAddress__c] [nvarchar] (1300) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[hed__Geolocation__Latitude__s] [float] NULL,
[hed__Geolocation__Longitude__s] [float] NULL,
[hed__Latest_End_Date__c] [date] NULL,
[hed__Latest_Start_Date__c] [date] NULL,
[hed__MailingCity__c] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[hed__MailingCountry__c] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[hed__MailingPostalCode__c] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[hed__MailingState__c] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[hed__MailingStreet2__c] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[hed__MailingStreet__c] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[hed__Parent_Account__c] [nvarchar] (18) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[hed__Parent_Contact__c] [nvarchar] (18) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[hed__Seasonal_End_Day__c] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[hed__Seasonal_End_Month__c] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[hed__Seasonal_End_Year__c] [float] NULL,
[hed__Seasonal_Start_Day__c] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[hed__Seasonal_Start_Month__c] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[hed__Seasonal_Start_Year__c] [float] NULL,
[copyloaddate] [datetime] NULL CONSTRAINT [DF__hed_Addre__copyl__282DF8C2] DEFAULT (getdate())
)
GO
